"""修改志愿序号可重复

Revision ID: 06475a15bd11
Revises: 76765d186b8d
Create Date: 2025-04-11 13:53:28.541124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06475a15bd11'
down_revision = '76765d186b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_colleges', schema=None) as batch_op:
        batch_op.drop_index('unique_volunteer_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_colleges', schema=None) as batch_op:
        batch_op.create_index('unique_volunteer_index', ['plan_id', 'volunteer_index'], unique=True)

    # ### end Alembic commands ###
