"""增加admin角色

Revision ID: 0c66486b845c
Revises: 52425fd813e7
Create Date: 2025-04-17 15:20:55.327642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c66486b845c'
down_revision = '52425fd813e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college_preferences', schema=None) as batch_op:
        batch_op.alter_column('strategy',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='填报策略：冲刺院校，兼顾专业 or 冲刺专业方向，院校其次',
               existing_comment='填报策略：院校优先 or 专业优先',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college_preferences', schema=None) as batch_op:
        batch_op.alter_column('strategy',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='填报策略：院校优先 or 专业优先',
               existing_comment='填报策略：冲刺院校，兼顾专业 or 冲刺专业方向，院校其次',
               existing_nullable=True)

    # ### end Alembic commands ###
