"""修改成绩字段为字符

Revision ID: 11e929778ec0
Revises: 1926f76e4488
Create Date: 2025-03-28 17:32:40.958048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11e929778ec0'
down_revision = '1926f76e4488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_records', schema=None) as batch_op:
        batch_op.alter_column('gaokao_total_score',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='高考总分',
               existing_nullable=True)
        batch_op.alter_column('gaokao_ranking',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='高考位次',
               existing_nullable=True)
        batch_op.alter_column('standard_score',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=20),
               existing_comment='标准分数',
               existing_nullable=True)
        batch_op.alter_column('chinese_score',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='语文成绩',
               existing_nullable=True)
        batch_op.alter_column('math_score',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='数学成绩',
               existing_nullable=True)
        batch_op.alter_column('foreign_lang_score',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='外语成绩',
               existing_nullable=True)
        batch_op.alter_column('physics_score',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='物理成绩',
               existing_nullable=True)
        batch_op.alter_column('history_score',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='历史成绩',
               existing_nullable=True)
        batch_op.alter_column('chemistry_score',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='化学成绩',
               existing_nullable=True)
        batch_op.alter_column('biology_score',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='生物成绩',
               existing_nullable=True)
        batch_op.alter_column('geography_score',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='地理成绩',
               existing_nullable=True)
        batch_op.alter_column('politics_score',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='政治成绩',
               existing_nullable=True)
        batch_op.alter_column('mock_exam1_score',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='第一次模考成绩',
               existing_nullable=True)
        batch_op.alter_column('mock_exam2_score',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='第二次模考成绩',
               existing_nullable=True)
        batch_op.alter_column('mock_exam3_score',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_comment='第三次模考成绩',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_records', schema=None) as batch_op:
        batch_op.alter_column('mock_exam3_score',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='第三次模考成绩',
               existing_nullable=True)
        batch_op.alter_column('mock_exam2_score',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='第二次模考成绩',
               existing_nullable=True)
        batch_op.alter_column('mock_exam1_score',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='第一次模考成绩',
               existing_nullable=True)
        batch_op.alter_column('politics_score',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='政治成绩',
               existing_nullable=True)
        batch_op.alter_column('geography_score',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='地理成绩',
               existing_nullable=True)
        batch_op.alter_column('biology_score',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='生物成绩',
               existing_nullable=True)
        batch_op.alter_column('chemistry_score',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='化学成绩',
               existing_nullable=True)
        batch_op.alter_column('history_score',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='历史成绩',
               existing_nullable=True)
        batch_op.alter_column('physics_score',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='物理成绩',
               existing_nullable=True)
        batch_op.alter_column('foreign_lang_score',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='外语成绩',
               existing_nullable=True)
        batch_op.alter_column('math_score',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='数学成绩',
               existing_nullable=True)
        batch_op.alter_column('chinese_score',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='语文成绩',
               existing_nullable=True)
        batch_op.alter_column('standard_score',
               existing_type=sa.String(length=20),
               type_=mysql.FLOAT(),
               existing_comment='标准分数',
               existing_nullable=True)
        batch_op.alter_column('gaokao_ranking',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='高考位次',
               existing_nullable=True)
        batch_op.alter_column('gaokao_total_score',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_comment='高考总分',
               existing_nullable=True)

    # ### end Alembic commands ###
