"""学生志愿表增加新字段

Revision ID: 14ed16bf17ba
Revises: 19be23cdcda9
Create Date: 2025-04-03 11:44:26.854343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ed16bf17ba'
down_revision = '19be23cdcda9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_volunteer_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_data_hash', sa.String(length=64), nullable=True, comment='用户数据哈希，用于检测用户数据是否变化'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_volunteer_plans', schema=None) as batch_op:
        batch_op.drop_column('user_data_hash')

    # ### end Alembic commands ###
