"""学生信息添加身份证和失信原因

Revision ID: 1926f76e4488
Revises: f09f4593d239
Create Date: 2025-03-28 17:29:31.369367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1926f76e4488'
down_revision = 'f09f4593d239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zwh_xgk_zuidifen_2021', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_zuidifen_2021')
    with op.batch_alter_table('zwh_xgk_fenshuxian_2022_2025', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_fenshuxian_2022_2025')
    with op.batch_alter_table('zwh_xgk_zuidifen_2024', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_zuidifen_2024')
    op.drop_table('zwh_xgk_fenzu_2025')
    with op.batch_alter_table('zwh_xgk_fenshuxian_2025', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_fenshuxian_2025')
    with op.batch_alter_table('zwh_areas', schema=None) as batch_op:
        batch_op.drop_index('idx_shudi_aid')

    op.drop_table('zwh_areas')
    op.drop_table('zwh_xgk_zhuanye_2025')
    with op.batch_alter_table('zwh_xgk_zuidifen_2023', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_zuidifen_2023')
    op.drop_table('zwh_divisions')
    with op.batch_alter_table('zwh_xgk_zuidifen_2022', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_zuidifen_2022')
    with op.batch_alter_table('zwh_xgk_fenshuxian_2024', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_fenshuxian_2024')
    op.drop_table('zwh_xgk_yuanxiao_2025')
    op.drop_table('zwh_xgk_jihua_2025')
    with op.batch_alter_table('zwh_xgk_fenshuxian_2021', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_fenshuxian_2021')
    op.drop_table('zwh_specialties_type')
    with op.batch_alter_table('zwh_xgk_fenshuxian_2023', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_fenshuxian_2023')
    op.drop_table('zwh_xgk_picixian')
    op.drop_table('zwh_scorerank')
    with op.batch_alter_table('zwh_xgk_fenshuxian_2022', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_fenshuxian_2022')
    with op.batch_alter_table('zwh_xgk_zuidifen_2025', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_zuidifen_2025')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_card_number', sa.String(length=18), nullable=True, comment='身份证号'))
        batch_op.add_column(sa.Column('discredit_reason', sa.String(length=500), nullable=True, comment='失信原因'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('discredit_reason')
        batch_op.drop_column('id_card_number')

    op.create_table('zwh_xgk_zuidifen_2025',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='学校'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业:新专业id：用于和最新专业名称对齐'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('xuezhi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学制：对应几年制'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始id:存储原始专业名称'),
    sa.Column('shuoming', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='专业特殊说明'),
    sa.Column('cgname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='分组名称'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.Column('baoyan', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True, comment='保研'),
    sa.Column('teacher', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True, comment='教师'),
    sa.Column('doctor', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True, comment='医生'),
    sa.Column('official', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True, comment='公务员'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_zuidifen_2025', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_xgk_fenshuxian_2022',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='高校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_fenshuxian_2022', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_scorerank',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('scores', mysql.INTEGER(), autoincrement=False, nullable=True, comment='分值'),
    sa.Column('nums', mysql.INTEGER(), autoincrement=False, nullable=True, comment='排位'),
    sa.Column('suid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='科别'),
    sa.PrimaryKeyConstraint('id'),
    comment='排位管理',
    mysql_comment='排位管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('zwh_xgk_picixian',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('dyear', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('dscore', mysql.DECIMAL(precision=11, scale=0), nullable=True, comment='省定分数线'),
    sa.Column('aid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='省份'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('remarks', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='remarks'),
    sa.Column('numplan', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('numabove', mysql.INTEGER(), autoincrement=False, nullable=True, comment='达线人数'),
    sa.Column('newbid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('numplan_new', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数合并后'),
    sa.Column('numabove_new', mysql.INTEGER(), autoincrement=False, nullable=True, comment='达线人数合并后'),
    sa.PrimaryKeyConstraint('id'),
    comment='省定线表',
    mysql_comment='省定线表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('zwh_xgk_fenshuxian_2023',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='高校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_fenshuxian_2023', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_specialties_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sptfather', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='上级专业'),
    sa.Column('sptname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='名称'),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=True, comment='sort'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('zwh_xgk_fenshuxian_2021',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='高校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True, comment='专业'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_fenshuxian_2021', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_xgk_jihua_2025',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('json_data', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('fsx_id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('zwh_xgk_yuanxiao_2025',
    sa.Column('cid', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('aid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='高校名称'),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=True, comment='热门高校排序'),
    sa.Column('uncode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='高校代码'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tese', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='学校特色'),
    sa.Column('leixing', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), server_default=sa.text("'1'"), nullable=True, comment='学校类型'),
    sa.Column('xingzhi', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='学校性质'),
    sa.Column('baoyan', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='保研'),
    sa.Column('minxuefei', mysql.INTEGER(), autoincrement=False, nullable=True, comment='最低学费'),
    sa.Column('maxxuefei', mysql.INTEGER(), autoincrement=False, nullable=True, comment='最高学费'),
    sa.Column('teshu', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='特殊类型'),
    sa.PrimaryKeyConstraint('cid'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('zwh_xgk_fenshuxian_2024',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='学校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_fenshuxian_2024', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_xgk_zuidifen_2022',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='高校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_zuidifen_2022', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_divisions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('dyear', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('dscore', mysql.DECIMAL(precision=11, scale=0), nullable=True, comment='省定分数线'),
    sa.Column('aid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='省份'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('remarks', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='备注'),
    sa.Column('numplan', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('numabove', mysql.INTEGER(), autoincrement=False, nullable=True, comment='达线人数'),
    sa.PrimaryKeyConstraint('id'),
    comment='省定线表',
    mysql_comment='省定线表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('zwh_xgk_zuidifen_2023',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='高校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_zuidifen_2023', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_xgk_zhuanye_2025',
    sa.Column('spid', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业名称'),
    sa.Column('spfather', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='上级专业'),
    sa.Column('content', mysql.TEXT(charset='utf8', collation='utf8_general_ci'), nullable=True, comment='专业介绍'),
    sa.Column('subclassid', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='Subclassid'),
    sa.Column('teacher', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=6), server_default=sa.text("'否'"), nullable=True, comment='教师'),
    sa.Column('doctor', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=6), server_default=sa.text("'否'"), nullable=True, comment='医生'),
    sa.Column('official', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=6), server_default=sa.text("'否'"), nullable=True, comment='公务员'),
    sa.PrimaryKeyConstraint('spid'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('zwh_areas',
    sa.Column('aid', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('aname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='名称'),
    sa.Column('afather', mysql.INTEGER(), autoincrement=False, nullable=True, comment='上级ID'),
    sa.Column('pid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='类别'),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.PrimaryKeyConstraint('aid'),
    comment='地区地域表',
    mysql_comment='地区地域表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_areas', schema=None) as batch_op:
        batch_op.create_index('idx_shudi_aid', ['aid'], unique=False)

    op.create_table('zwh_xgk_fenshuxian_2025',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='学校'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业:新专业id：用于和最新专业名称对齐'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('xuezhi', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True, comment='学制：对应几年制'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始id:存储原始专业名称'),
    sa.Column('shuoming', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='专业特殊说明'),
    sa.Column('cgname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='分组名称'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.Column('baoyan', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True, comment='保研'),
    sa.Column('teacher', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True, comment='教师'),
    sa.Column('doctor', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True, comment='医生'),
    sa.Column('official', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True, comment='公务员'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_fenshuxian_2025', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_xgk_fenzu_2025',
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=False, comment='院校专业组的ID'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('newsuid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应首选科目：1、历史；2、物理'),
    sa.Column('oldcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='老的院校id'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新的院校ID主要是统一uncode相同的院校'),
    sa.Column('uncode', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='院校招生代码'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('oldcgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='记录之前历年信息表中存储的分组id'),
    sa.Column('minxuefei', mysql.INTEGER(), autoincrement=False, nullable=True, comment='最低学费'),
    sa.Column('maxxuefei', mysql.INTEGER(), autoincrement=False, nullable=True, comment='最高学费'),
    sa.Column('teshu', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='特殊类型'),
    sa.Column('cgname', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='专业组名称'),
    sa.PrimaryKeyConstraint('cgid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('zwh_xgk_zuidifen_2024',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='学校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_zuidifen_2024', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_xgk_fenshuxian_2022_2025',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='学校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_fenshuxian_2022_2025', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_xgk_zuidifen_2021',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='高校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True, comment='专业'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_zuidifen_2021', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    # ### end Alembic commands ###
