"""学生志愿表增加新字段

Revision ID: 19be23cdcda9
Revises: f7f46fc97255
Create Date: 2025-04-03 10:30:21.413069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19be23cdcda9'
down_revision = 'f7f46fc97255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_colleges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_name', sa.String(length=100), nullable=True, comment='地区名称，如"河南省郑州市"'))
        batch_op.add_column(sa.Column('group_name', sa.String(length=100), nullable=True, comment='专业组名称，如"第121组"'))
        batch_op.add_column(sa.Column('min_tuition', sa.Integer(), nullable=True, comment='最低学费'))
        batch_op.add_column(sa.Column('max_tuition', sa.Integer(), nullable=True, comment='最高学费'))
        batch_op.add_column(sa.Column('min_score', sa.Integer(), nullable=True, comment='最低分数'))
        batch_op.add_column(sa.Column('plan_number', sa.Integer(), nullable=True, comment='计划招生人数'))
        batch_op.add_column(sa.Column('school_type_text', sa.String(length=50), nullable=True, comment='学校类型文本，如"工科"'))
        batch_op.add_column(sa.Column('subject_requirements', sa.JSON(), nullable=True, comment='选科要求，格式为JSON对象'))
        batch_op.add_column(sa.Column('tese_text', sa.JSON(), nullable=True, comment='特色文本数组，如["省部共建", "硕博点"]'))
        batch_op.add_column(sa.Column('teshu_text', sa.JSON(), nullable=True, comment='特殊类型文本数组'))
        batch_op.add_column(sa.Column('uncode', sa.String(length=20), nullable=True, comment='院校代码，如"6110"'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_colleges', schema=None) as batch_op:
        batch_op.drop_column('uncode')
        batch_op.drop_column('teshu_text')
        batch_op.drop_column('tese_text')
        batch_op.drop_column('subject_requirements')
        batch_op.drop_column('school_type_text')
        batch_op.drop_column('plan_number')
        batch_op.drop_column('min_score')
        batch_op.drop_column('max_tuition')
        batch_op.drop_column('min_tuition')
        batch_op.drop_column('group_name')
        batch_op.drop_column('area_name')

    # ### end Alembic commands ###
