"""添加会话和消息表

Revision ID: 200600636742
Revises: 2307d7265dd6
Create Date: 2025-04-12 09:39:31.058939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200600636742'
down_revision = '2307d7265dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生ID'),
    sa.Column('planner_id', sa.Integer(), nullable=False, comment='规划师ID'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='会话标题'),
    sa.Column('conversation_type', sa.String(length=20), nullable=True, comment='会话类型'),
    sa.Column('last_message_time', sa.DateTime(), nullable=True, comment='最后消息时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否活跃'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='是否归档'),
    sa.Column('meta_data', sa.Text(), nullable=True, comment='会话相关元数据，如关联专业、院校等信息'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['planner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('idx_last_message', ['last_message_time'], unique=False)
        batch_op.create_index('idx_student_planner', ['student_id', 'planner_id'], unique=False)

    op.create_table('messages',
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('sender_id', sa.Integer(), nullable=True, comment='发送者ID，系统或AI消息为空'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色'),
    sa.Column('message_type', sa.String(length=20), nullable=True, comment='消息类型'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_conversation', ['conversation_id'], unique=False)
        batch_op.create_index('idx_conversation_created', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index('idx_sender', ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_sender')
        batch_op.drop_index('idx_conversation_created')
        batch_op.drop_index('idx_conversation')

    op.drop_table('messages')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_student_planner')
        batch_op.drop_index('idx_last_message')

    op.drop_table('conversations')
    # ### end Alembic commands ###
