"""恢复学生志愿专业中的unique_specialty_index

Revision ID: 2307d7265dd6
Revises: f61423915c73
Create Date: 2025-04-11 17:36:33.241139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2307d7265dd6'
down_revision = 'f61423915c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_specialties', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_specialty_index', ['volunteer_college_id', 'specialty_index'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_specialties', schema=None) as batch_op:
        batch_op.drop_constraint('unique_specialty_index', type_='unique')

    # ### end Alembic commands ###
