"""增加大模型配置数据表

Revision ID: 2ada07ee89a9
Revises: acf4efbcddf9
Create Date: 2025-04-18 16:23:05.312219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ada07ee89a9'
down_revision = 'acf4efbcddf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_configurations',
    sa.Column('provider', sa.String(length=50), nullable=False, comment='提供者名称(moonshot/deepseek/zhipu等)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_configurations')
    # ### end Alembic commands ###
