"""学生基础信息字段调整

Revision ID: 2b1ca796bb62
Revises: f72c7432c039
Create Date: 2025-04-21 13:59:20.268134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1ca796bb62'
down_revision = 'f72c7432c039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_condition', sa.String(length=500), nullable=True, comment='其他情况'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('other_condition')

    # ### end Alembic commands ###
