"""增加学生志愿相关表

Revision ID: 468d8dec1fbe
Revises: bd60d6ce04db
Create Date: 2025-04-02 10:51:15.959963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468d8dec1fbe'
down_revision = 'bd60d6ce04db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_specialties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fenshuxian_id', sa.Integer(), nullable=True, comment='关联到分数线表(zwh_xgk_fenshuxian_2025)的ID'))
        batch_op.create_index('idx_fenshuxian', ['fenshuxian_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_specialties', schema=None) as batch_op:
        batch_op.drop_index('idx_fenshuxian')
        batch_op.drop_column('fenshuxian_id')

    # ### end Alembic commands ###
