"""添加测评表

Revision ID: 4efd0f6a0267
Revises: caaf9b45ebe3
Create Date: 2025-04-25 11:56:57.687170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4efd0f6a0267'
down_revision = 'caaf9b45ebe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ceping_job_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True, comment='学生ID'))

    with op.batch_alter_table('ceping_mbti_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True, comment='学生ID'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ceping_mbti_answer', schema=None) as batch_op:
        batch_op.drop_column('student_id')

    with op.batch_alter_table('ceping_job_answer', schema=None) as batch_op:
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
