"""添加会话和消息表

Revision ID: 52425fd813e7
Revises: 200600636742
Create Date: 2025-04-12 10:08:15.237486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52425fd813e7'
down_revision = '200600636742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('conversations_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('conversations_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('messages_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('messages_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_ibfk_1', 'conversations', ['conversation_id'], ['id'])
        batch_op.create_foreign_key('messages_ibfk_2', 'users', ['sender_id'], ['id'])

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_foreign_key('conversations_ibfk_1', 'users', ['planner_id'], ['id'])
        batch_op.create_foreign_key('conversations_ibfk_2', 'users', ['student_id'], ['id'])

    # ### end Alembic commands ###
