"""移除unique_specialty_index限制

Revision ID: 5fa33569d934
Revises: 9dc4c122a4b4
Create Date: 2025-04-11 14:54:58.593847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa33569d934'
down_revision = '9dc4c122a4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_specialties', schema=None) as batch_op:
        batch_op.drop_index('unique_specialty_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_specialties', schema=None) as batch_op:
        batch_op.create_index('unique_specialty_index', ['volunteer_college_id', 'specialty_index'], unique=True)

    # ### end Alembic commands ###
