"""修改志愿表绑定的学生id

Revision ID: 6d08a02bb2be
Revises: fb1500c4bc8b
Create Date: 2025-04-30 17:01:37.598471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d08a02bb2be'
down_revision = 'fb1500c4bc8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_volunteer_plans', schema=None) as batch_op:
        batch_op.drop_constraint('student_volunteer_plans_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_volunteer_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_volunteer_plans_ibfk_2', 'users', ['student_id'], ['id'])

    # ### end Alembic commands ###
