"""添加咨询师信息

Revision ID: 78ce032f062a
Revises: 11e929778ec0
Create Date: 2025-03-31 11:11:32.573469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ce032f062a'
down_revision = '11e929778ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner_info',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联的用户ID'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='地址'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planner_info')
    # ### end Alembic commands ###
