"""修改身高体重字段

Revision ID: 79404cb7121b
Revises: 97e6deee9007
Create Date: 2025-04-01 09:58:38.577208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79404cb7121b'
down_revision = '97e6deee9007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=10),
               existing_comment='身高(CM)',
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=10),
               existing_comment='体重(KG)',
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['planner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_ibfk_1', 'users', ['planner_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.String(length=10),
               type_=mysql.FLOAT(),
               existing_comment='体重(KG)',
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.String(length=10),
               type_=mysql.FLOAT(),
               existing_comment='身高(CM)',
               existing_nullable=True)

    # ### end Alembic commands ###
