"""添加院校信息

Revision ID: 97e6deee9007
Revises: 78ce032f062a
Create Date: 2025-03-31 11:24:38.741082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97e6deee9007'
down_revision = '78ce032f062a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zwh_xgk_zuidifen_2021', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_zuidifen_2021')
    with op.batch_alter_table('zwh_xgk_zuidifen_2025', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_zuidifen_2025')
    with op.batch_alter_table('zwh_xgk_fenshuxian_2022_2025', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_fenshuxian_2022_2025')
    with op.batch_alter_table('zwh_xgk_zuidifen_2023', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_zuidifen_2023')
    with op.batch_alter_table('zwh_xgk_zuidifen_2024', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_zuidifen_2024')
    with op.batch_alter_table('zwh_xgk_zuidifen_2022', schema=None) as batch_op:
        batch_op.drop_index('default')

    op.drop_table('zwh_xgk_zuidifen_2022')
    with op.batch_alter_table('zwh_areas', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='地区地域表'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zwh_areas', schema=None) as batch_op:
        batch_op.create_table_comment(
        '地区地域表',
        existing_comment=None
    )

    op.create_table('zwh_xgk_zuidifen_2022',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='高校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_zuidifen_2022', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_xgk_zuidifen_2024',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='学校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_zuidifen_2024', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_xgk_zuidifen_2023',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='高校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_zuidifen_2023', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_xgk_fenshuxian_2022_2025',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='学校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_fenshuxian_2022_2025', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_xgk_zuidifen_2025',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='学校'),
    sa.Column('spid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业:新专业id：用于和最新专业名称对齐'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('xuezhi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学制：对应几年制'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始id:存储原始专业名称'),
    sa.Column('shuoming', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='专业特殊说明'),
    sa.Column('cgname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='分组名称'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.Column('baoyan', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True, comment='保研'),
    sa.Column('teacher', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True, comment='教师'),
    sa.Column('doctor', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True, comment='医生'),
    sa.Column('official', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True, comment='公务员'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_zuidifen_2025', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    op.create_table('zwh_xgk_zuidifen_2021',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('cid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='高校'),
    sa.Column('spid_init', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='专业原始ID'),
    sa.Column('bid', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='批次'),
    sa.Column('csbscore', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际分数'),
    sa.Column('csbplannum', mysql.INTEGER(), autoincrement=False, nullable=True, comment='计划人数'),
    sa.Column('suid', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='科别'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('tuitions', mysql.INTEGER(), autoincrement=False, nullable=True, comment='学费'),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年份'),
    sa.Column('spcode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业代码'),
    sa.Column('zyfx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='专业方向'),
    sa.Column('bhzy', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='包含专业'),
    sa.Column('tslx', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='特殊类型'),
    sa.Column('yuce', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='预测分数'),
    sa.Column('rengong', mysql.INTEGER(), autoincrement=False, nullable=True, comment='人工修正分数'),
    sa.Column('wu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='物理：1、必选；2无要求'),
    sa.Column('shi', mysql.INTEGER(), autoincrement=False, nullable=True, comment='历史：1、必选；2无要求'),
    sa.Column('hua', mysql.INTEGER(), autoincrement=False, nullable=True, comment='化学：1、必选；2无要求'),
    sa.Column('sheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生物：1、必选；2无要求'),
    sa.Column('di', mysql.INTEGER(), autoincrement=False, nullable=True, comment='地理：1、必选；2无要求'),
    sa.Column('zheng', mysql.INTEGER(), autoincrement=False, nullable=True, comment='政治：1、必选；2无要求'),
    sa.Column('fenzu', mysql.INTEGER(), autoincrement=False, nullable=True, comment='根据选课要求重建的分组'),
    sa.Column('cgid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='院校专业组ID'),
    sa.Column('newcid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='新院校ID对应zwh_college_groups_2024表'),
    sa.Column('newbid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='对应新批次：11、本科；12、专科'),
    sa.Column('spid', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True, comment='专业'),
    sa.Column('spname', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=2500), nullable=True, comment='对应spid的专业名称'),
    sa.Column('subclassid', mysql.INTEGER(), autoincrement=False, nullable=True, comment='专业类ID'),
    sa.Column('weici', mysql.INTEGER(), autoincrement=False, nullable=True, comment='位次'),
    sa.PrimaryKeyConstraint('id'),
    comment='历史分数线管理',
    mysql_comment='历史分数线管理',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('zwh_xgk_zuidifen_2021', schema=None) as batch_op:
        batch_op.create_index('default', ['cid', 'spid_init', 'bid', 'csbscore', 'csbplannum', 'suid', 'status', 'tuitions', 'year'], unique=False)

    # ### end Alembic commands ###
