"""添加志愿类别分析状态常量

Revision ID: 9bd5680d3617
Revises: f12404ed2bde
Create Date: 2025-04-07 13:57:03.668999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd5680d3617'
down_revision = 'f12404ed2bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_category_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息，当状态为failed时有值'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_category_analyses', schema=None) as batch_op:
        batch_op.drop_column('error_message')

    # ### end Alembic commands ###
