"""修改志愿序号为数字

Revision ID: 9dc4c122a4b4
Revises: 06475a15bd11
Create Date: 2025-04-11 14:09:50.331407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9dc4c122a4b4'
down_revision = '06475a15bd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_colleges', schema=None) as batch_op:
        batch_op.alter_column('volunteer_index',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Integer(),
               existing_comment='志愿在方案中的序号(1-48)',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_colleges', schema=None) as batch_op:
        batch_op.alter_column('volunteer_index',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_comment='志愿在方案中的序号(1-48)',
               existing_nullable=False)

    # ### end Alembic commands ###
