"""增加家庭背景字段

Revision ID: 9f829416925b
Revises: 2b1ca796bb62
Create Date: 2025-04-21 14:33:44.961408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f829416925b'
down_revision = '2b1ca796bb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_background', sa.Text(), nullable=True, comment='家庭背景详细描述，包括家庭经济状况、父母职业、教育背景等'))
        batch_op.alter_column('application_preference',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='其他意向',
               existing_comment='报考倾向：家庭背景资源、意向院校以及专业等情况的详细描述',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college_preferences', schema=None) as batch_op:
        batch_op.alter_column('application_preference',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='报考倾向：家庭背景资源、意向院校以及专业等情况的详细描述',
               existing_comment='其他意向',
               existing_nullable=True)
        batch_op.drop_column('family_background')

    # ### end Alembic commands ###
