"""添加机构表

Revision ID: ac570c016e12
Revises: 9f829416925b
Create Date: 2025-04-24 15:32:51.538155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac570c016e12'
down_revision = '9f829416925b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('name', sa.String(length=100), nullable=False, comment='机构名称'),
    sa.Column('address', sa.String(length=200), nullable=True, comment='机构地址'),
    sa.Column('qrcode_path', sa.String(length=255), nullable=True, comment='机构二维码图片路径'),
    sa.Column('logo_path', sa.String(length=255), nullable=True, comment='机构logo图片路径'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('contact_email', sa.String(length=100), nullable=True, comment='联系邮箱'),
    sa.Column('description', sa.Text(), nullable=True, comment='机构描述'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态：1-激活, 0-禁用'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.Integer(), nullable=True, comment='所属机构ID'))
        batch_op.create_foreign_key(None, 'institutions', ['institution_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('institution_id')

    op.drop_table('institutions')
    # ### end Alembic commands ###
