"""增加提示词管理

Revision ID: acf4efbcddf9
Revises: 0c66486b845c
Create Date: 2025-04-18 14:34:00.873776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf4efbcddf9'
down_revision = '0c66486b845c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=100), nullable=False, comment='提示词名称'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='提示词类型'),
    sa.Column('content', sa.Text(), nullable=False, comment='提示词内容'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='提示词描述'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
