"""添加学生信息

Revision ID: b4f11439bce3
Revises: e9199b190966
Create Date: 2025-03-26 14:56:30.814245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4f11439bce3'
down_revision = 'e9199b190966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_discredited', sa.Boolean(), nullable=True, comment='是否失信考生'))
        batch_op.drop_column('is_feeling_lost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_feeling_lost', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否迷失在学生'))
        batch_op.drop_column('is_discredited')

    # ### end Alembic commands ###
