"""用户表添加学生咨询状态字段

Revision ID: bd39e4b0253e
Revises: c62e84678c61
Create Date: 2025-04-09 14:54:57.568348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd39e4b0253e'
down_revision = 'c62e84678c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultation_status', sa.String(length=20), nullable=True, comment='学生用户咨询状态'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('consultation_status')

    # ### end Alembic commands ###
