"""添加每版志愿方案学生信息变化

Revision ID: c31ca4af413c
Revises: 9bd5680d3617
Create Date: 2025-04-09 11:14:57.981084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31ca4af413c'
down_revision = '9bd5680d3617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_volunteer_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_data_snapshot', sa.Text(), nullable=True, comment='生成方案时的学生数据快照，JSON格式'))
        batch_op.add_column(sa.Column('data_changes', sa.Text(), nullable=True, comment='与上一版方案相比的数据变化描述'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_volunteer_plans', schema=None) as batch_op:
        batch_op.drop_column('data_changes')
        batch_op.drop_column('student_data_snapshot')

    # ### end Alembic commands ###
