"""修改模考字段为一个

Revision ID: c62e84678c61
Revises: c31ca4af413c
Create Date: 2025-04-09 13:59:34.883949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c62e84678c61'
down_revision = 'c31ca4af413c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mock_exam_score', sa.String(length=20), nullable=True, comment='模考成绩'))
        batch_op.drop_column('mock_exam2_score')
        batch_op.drop_column('mock_exam3_score')
        batch_op.drop_column('mock_exam1_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mock_exam1_score', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='第一次模考成绩'))
        batch_op.add_column(sa.Column('mock_exam3_score', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='第三次模考成绩'))
        batch_op.add_column(sa.Column('mock_exam2_score', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='第二次模考成绩'))
        batch_op.drop_column('mock_exam_score')

    # ### end Alembic commands ###
