"""添加测评表

Revision ID: caaf9b45ebe3
Revises: ac570c016e12
Create Date: 2025-04-25 11:55:32.566982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'caaf9b45ebe3'
down_revision = 'ac570c016e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ceping_job_answer', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('agent_id')
        batch_op.drop_column('phone')
        batch_op.drop_column('sex')
        batch_op.drop_column('school')
        batch_op.drop_column('username')

    with op.batch_alter_table('ceping_mbti_answer', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('agent_id')
        batch_op.drop_column('phone')
        batch_op.drop_column('chengji')
        batch_op.drop_column('sex')
        batch_op.drop_column('school')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ceping_mbti_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='姓名'))
        batch_op.add_column(sa.Column('school', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='学校名称'))
        batch_op.add_column(sa.Column('sex', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='性别'))
        batch_op.add_column(sa.Column('chengji', mysql.TEXT(charset='utf8', collation='utf8_general_ci'), nullable=True, comment='成绩'))
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='电话号码'))
        batch_op.add_column(sa.Column('agent_id', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='代理商ID'))
        batch_op.add_column(sa.Column('year', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='高考年份'))

    with op.batch_alter_table('ceping_job_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='姓名'))
        batch_op.add_column(sa.Column('school', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='学校名称'))
        batch_op.add_column(sa.Column('sex', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='性别'))
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='电话号码'))
        batch_op.add_column(sa.Column('agent_id', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=True, comment='代理商ID'))
        batch_op.add_column(sa.Column('year', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=250), nullable=True, comment='高考年份'))

    # ### end Alembic commands ###
