"""学生志愿表增加新字段

Revision ID: ddffedd18bed
Revises: 14ed16bf17ba
Create Date: 2025-04-03 15:58:02.387642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddffedd18bed'
down_revision = '14ed16bf17ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_colleges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nature', sa.String(length=20), nullable=True, comment='院校性质，如"公办"'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_colleges', schema=None) as batch_op:
        batch_op.drop_column('nature')

    # ### end Alembic commands ###
