"""添加学生信息

Revision ID: e9199b190966
Revises: f54af9aab3d6
Create Date: 2025-03-26 14:54:20.180896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9199b190966'
down_revision = 'f54af9aab3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='学生姓名'),
    sa.Column('gender', sa.String(length=10), nullable=False, comment='性别'),
    sa.Column('ethnicity', sa.String(length=50), nullable=True, comment='民族'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('wechat_qq', sa.String(length=50), nullable=True, comment='微信/QQ'),
    sa.Column('school', sa.String(length=100), nullable=True, comment='毕业学校'),
    sa.Column('address', sa.String(length=200), nullable=True, comment='家庭住址'),
    sa.Column('candidate_number', sa.String(length=50), nullable=True, comment='准考证号'),
    sa.Column('household_type', sa.String(length=20), nullable=True, comment='户籍类型'),
    sa.Column('student_type', sa.String(length=20), nullable=True, comment='考生类型'),
    sa.Column('guardian1_name', sa.String(length=50), nullable=True, comment='第一联系人姓名'),
    sa.Column('guardian1_phone', sa.String(length=20), nullable=True, comment='第一联系人电话'),
    sa.Column('guardian2_name', sa.String(length=50), nullable=True, comment='第二联系人姓名'),
    sa.Column('guardian2_phone', sa.String(length=20), nullable=True, comment='第二联系人电话'),
    sa.Column('left_eye_vision', sa.String(length=20), nullable=True, comment='左眼视力情况'),
    sa.Column('right_eye_vision', sa.String(length=20), nullable=True, comment='右眼视力情况'),
    sa.Column('color_vision', sa.String(length=20), nullable=True, comment='色觉情况'),
    sa.Column('height', sa.Float(), nullable=True, comment='身高(CM)'),
    sa.Column('weight', sa.Float(), nullable=True, comment='体重(KG)'),
    sa.Column('foreign_language', sa.String(length=100), nullable=True, comment='外语语种'),
    sa.Column('is_feeling_lost', sa.Boolean(), nullable=True, comment='是否迷失在学生'),
    sa.Column('strong_subjects', sa.String(length=200), nullable=True, comment='优势科目'),
    sa.Column('weak_subjects', sa.String(length=200), nullable=True, comment='劣势科目'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('academic_records',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('selected_subjects', sa.String(length=100), nullable=True, comment='高考选科'),
    sa.Column('gaokao_total_score', sa.Integer(), nullable=True, comment='高考总分'),
    sa.Column('gaokao_ranking', sa.Integer(), nullable=True, comment='高考位次'),
    sa.Column('standard_score', sa.Float(), nullable=True, comment='标准分数'),
    sa.Column('bonus_type', sa.String(length=50), nullable=True, comment='加分类型'),
    sa.Column('chinese_score', sa.Integer(), nullable=True, comment='语文成绩'),
    sa.Column('math_score', sa.Integer(), nullable=True, comment='数学成绩'),
    sa.Column('foreign_lang_score', sa.Integer(), nullable=True, comment='外语成绩'),
    sa.Column('physics_score', sa.Integer(), nullable=True, comment='物理成绩'),
    sa.Column('history_score', sa.Integer(), nullable=True, comment='历史成绩'),
    sa.Column('chemistry_score', sa.Integer(), nullable=True, comment='化学成绩'),
    sa.Column('biology_score', sa.Integer(), nullable=True, comment='生物成绩'),
    sa.Column('geography_score', sa.Integer(), nullable=True, comment='地理成绩'),
    sa.Column('politics_score', sa.Integer(), nullable=True, comment='政治成绩'),
    sa.Column('mock_exam1_score', sa.Integer(), nullable=True, comment='第一次模考成绩'),
    sa.Column('mock_exam2_score', sa.Integer(), nullable=True, comment='第二次模考成绩'),
    sa.Column('mock_exam3_score', sa.Integer(), nullable=True, comment='第三次模考成绩'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('academic_records')
    op.drop_table('students')
    # ### end Alembic commands ###
