"""学生基础信息字段调整

Revision ID: f0254f3d1977
Revises: 2ada07ee89a9
Create Date: 2025-04-21 10:17:12.875961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0254f3d1977'
down_revision = '2ada07ee89a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_detail', sa.String(length=200), nullable=True, comment='加分情况'))

    with op.batch_alter_table('college_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volunteer_gradient_strategy', sa.String(length=20), nullable=True, comment='志愿梯度策略：稳妥类型/激进类型/保底类型/自由设置'))
        batch_op.add_column(sa.Column('custom_gradient_counts', sa.JSON(), nullable=True, comment='自定义志愿梯度数量，JSON格式：{"chasing": 10, "stable": 15, "safe": 23}'))
        batch_op.add_column(sa.Column('application_batch', sa.String(length=50), nullable=True, comment='报考批次：本科批/专科批，多选'))
        batch_op.add_column(sa.Column('accept_nonchangeable_major', sa.Boolean(), nullable=True, comment='是否接受不可转专业中外合办专业'))
        batch_op.add_column(sa.Column('has_art_foundation', sa.Boolean(), nullable=True, comment='是否具备美术基础'))
        batch_op.add_column(sa.Column('accept_overseas_study', sa.Boolean(), nullable=True, comment='是否接受大学期间需出国就读'))
        batch_op.add_column(sa.Column('accept_high_fee_increase', sa.Boolean(), nullable=True, comment='是否接受学费刺客专业'))
        batch_op.add_column(sa.Column('accept_dual_city_arrangement', sa.Boolean(), nullable=True, comment='是否接受在两个城市上学安排'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('political_status', sa.String(length=20), nullable=True, comment='政治面貌'))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True, comment='出生日期'))
        batch_op.add_column(sa.Column('guardian1_relation', sa.String(length=20), nullable=True, comment='第一联系人关系'))
        batch_op.add_column(sa.Column('guardian2_relation', sa.String(length=20), nullable=True, comment='第二联系人关系'))
        batch_op.add_column(sa.Column('smell_condition', sa.String(length=20), nullable=True, comment='嗅觉情况'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('smell_condition')
        batch_op.drop_column('guardian2_relation')
        batch_op.drop_column('guardian1_relation')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('political_status')

    with op.batch_alter_table('college_preferences', schema=None) as batch_op:
        batch_op.drop_column('accept_dual_city_arrangement')
        batch_op.drop_column('accept_high_fee_increase')
        batch_op.drop_column('accept_overseas_study')
        batch_op.drop_column('has_art_foundation')
        batch_op.drop_column('accept_nonchangeable_major')
        batch_op.drop_column('application_batch')
        batch_op.drop_column('custom_gradient_counts')
        batch_op.drop_column('volunteer_gradient_strategy')

    with op.batch_alter_table('academic_records', schema=None) as batch_op:
        batch_op.drop_column('bonus_detail')

    # ### end Alembic commands ###
