"""增加学生志愿类别分析表

Revision ID: f12404ed2bde
Revises: ddffedd18bed
Create Date: 2025-04-07 10:27:36.376818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12404ed2bde'
down_revision = 'ddffedd18bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_category_analyses',
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='志愿方案ID'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='类别ID(1:冲, 2:稳, 3:保)'),
    sa.Column('analysis_content', sa.Text(), nullable=True, comment='AI分析内容'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='分析状态'),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True, comment='分析完成时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['student_volunteer_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'category_id', name='unique_plan_category')
    )
    with op.batch_alter_table('volunteer_category_analyses', schema=None) as batch_op:
        batch_op.create_index('idx_plan_category', ['plan_id', 'category_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_category_analyses', schema=None) as batch_op:
        batch_op.drop_index('idx_plan_category')

    op.drop_table('volunteer_category_analyses')
    # ### end Alembic commands ###
