"""学生志愿表加上cascade删除

Revision ID: f61423915c73
Revises: 5fa33569d934
Create Date: 2025-04-11 17:31:36.915123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61423915c73'
down_revision = '5fa33569d934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_specialties', schema=None) as batch_op:
        batch_op.drop_constraint('volunteer_specialties_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'volunteer_colleges', ['volunteer_college_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_specialties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('volunteer_specialties_ibfk_1', 'volunteer_colleges', ['volunteer_college_id'], ['id'])

    # ### end Alembic commands ###
