"""删除就业倾向表

Revision ID: f72c7432c039
Revises: f0254f3d1977
Create Date: 2025-04-21 10:42:46.299355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f72c7432c039'
down_revision = 'f0254f3d1977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_preferences', schema=None) as batch_op:
        batch_op.drop_constraint('career_preferences_ibfk_1', type_='foreignkey')
        batch_op.drop_index('student_id')

    op.drop_table('career_preferences')
    with op.batch_alter_table('college_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career_direction', sa.String(length=100), nullable=True, comment='就业发展方向，如金融,教师,医生等'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college_preferences', schema=None) as batch_op:
        batch_op.drop_column('career_direction')

    op.create_table('career_preferences',
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('career_direction', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='就业发展方向，如金融,教师,医生等'),
    sa.Column('academic_preference', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='学术学位偏好，如985,211等'),
    sa.Column('civil_service_preference', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='公务员意向'),
    sa.Column('employment_location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='就业地区'),
    sa.Column('income_expectation', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='职业稳定性与收入平衡'),
    sa.Column('work_stability', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='工作稳定性'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='career_preferences_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('career_preferences', schema=None) as batch_op:
        batch_op.create_index('student_id', ['student_id'], unique=True)

    # ### end Alembic commands ###