"""增加学生志愿相关表

Revision ID: f7f46fc97255
Revises: 468d8dec1fbe
Create Date: 2025-04-02 11:20:11.180515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f46fc97255'
down_revision = '468d8dec1fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_volunteer_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation_status', sa.String(length=20), nullable=True, comment='AI生成状态'))
        batch_op.add_column(sa.Column('generation_progress', sa.Integer(), nullable=True, comment='生成进度百分比(0-100)'))
        batch_op.add_column(sa.Column('generation_message', sa.String(length=255), nullable=True, comment='生成过程信息或错误信息'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_volunteer_plans', schema=None) as batch_op:
        batch_op.drop_column('generation_message')
        batch_op.drop_column('generation_progress')
        batch_op.drop_column('generation_status')

    # ### end Alembic commands ###
