"""添加规划师姓名

Revision ID: fb1500c4bc8b
Revises: 4efd0f6a0267
Create Date: 2025-04-30 10:24:18.608228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1500c4bc8b'
down_revision = '4efd0f6a0267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True, comment='姓名'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner_info', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
